apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cadvisor
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://ckotzbauer.github.io/helm-charts
      chart: cadvisor
      targetRevision: 2.3.3
      helm:
        releaseName: cadvisor
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring