apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  sources:
    - chart: istiod
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.22.0
    helm:
      releaseName: istio/istiod
      valueFiles: $values/istio/values.yaml
  - repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: istio-system
