apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 25.21.0
      helm:
        releaseName: prometheus
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring