apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph
      targetRevision: 1.14.3
      helm:
        releaseName: rook-ceph-operator
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: rook-ceph